// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolManagementSystem.Configurations.AppDbContext;

#nullable disable

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuruKelas", b =>
                {
                    b.Property<int>("KelasDiajarkanid_kelas")
                        .HasColumnType("integer");

                    b.Property<int>("Pengajarid_teacher")
                        .HasColumnType("integer");

                    b.HasKey("KelasDiajarkanid_kelas", "Pengajarid_teacher");

                    b.HasIndex("Pengajarid_teacher");

                    b.ToTable("KelasGuru", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Classes.Entities.Kelas", b =>
                {
                    b.Property<int>("id_kelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_kelas"));

                    b.Property<int?>("id_guru")
                        .HasColumnType("integer");

                    b.Property<string>("nama_kelas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_kelas");

                    b.HasIndex("id_guru");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Enrollments.Entities.Pendaftaran", b =>
                {
                    b.Property<int>("id_enrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_enrollment"));

                    b.Property<int>("id_kelas")
                        .HasColumnType("integer");

                    b.Property<int>("id_student")
                        .HasColumnType("integer");

                    b.Property<DateTime>("waktu_pendaftaran")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id_enrollment");

                    b.HasIndex("id_kelas");

                    b.HasIndex("id_student", "id_kelas")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Students.Entities.Murid", b =>
                {
                    b.Property<int>("id_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_student"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("waktu_registrasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_student");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Teachers.Entities.Guru", b =>
                {
                    b.Property<int>("id_teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_teacher"));

                    b.Property<string>("bidang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_teacher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nama_teacher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_teacher");

                    b.HasIndex("email_teacher")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GuruKelas", b =>
                {
                    b.HasOne("SchoolManagementSystem.Modules.Classes.Entities.Kelas", null)
                        .WithMany()
                        .HasForeignKey("KelasDiajarkanid_kelas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Modules.Teachers.Entities.Guru", null)
                        .WithMany()
                        .HasForeignKey("Pengajarid_teacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Classes.Entities.Kelas", b =>
                {
                    b.HasOne("SchoolManagementSystem.Modules.Teachers.Entities.Guru", "GuruUtama")
                        .WithMany("KelasUtama")
                        .HasForeignKey("id_guru")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuruUtama");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Enrollments.Entities.Pendaftaran", b =>
                {
                    b.HasOne("SchoolManagementSystem.Modules.Classes.Entities.Kelas", "kelas")
                        .WithMany("Enrollments")
                        .HasForeignKey("id_kelas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementSystem.Modules.Students.Entities.Murid", "Murid")
                        .WithMany("Enrollments")
                        .HasForeignKey("id_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Murid");

                    b.Navigation("kelas");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Classes.Entities.Kelas", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Students.Entities.Murid", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolManagementSystem.Modules.Teachers.Entities.Guru", b =>
                {
                    b.Navigation("KelasUtama");
                });
#pragma warning restore 612, 618
        }
    }
}
